"""Generates ready-to-upload fix files: recommended robots.txt, llms.txt,
schema JSON-LD templates, and an .htaccess snippet. Written into the
audit output folder so they can be edited and uploaded to the host."""

import json
from datetime import date
from urllib.parse import urlparse


def _origin(url: str) -> str:
    if not url.startswith(("http://", "https://")):
        url = "https://" + url
    p = urlparse(url)
    return f"{p.scheme}://{p.netloc}"


def recommended_robots_txt(url: str, block_training_bots: bool = False) -> str:
    origin = _origin(url)
    lines = [
        "# robots.txt - generated by SEO Audit Pro " + date.today().isoformat(),
        "# Search engine crawlers: full access",
        "User-agent: *",
        "Disallow:",
        "",
        "# --- AI answer engines (keep ALLOWED for visibility in",
        "# --- AI Overviews, ChatGPT Search, Perplexity, Claude) ---",
        "User-agent: GPTBot",
        "Allow: /",
        "",
        "User-agent: OAI-SearchBot",
        "Allow: /",
        "",
        "User-agent: ChatGPT-User",
        "Allow: /",
        "",
        "User-agent: ClaudeBot",
        "Allow: /",
        "",
        "User-agent: PerplexityBot",
        "Allow: /",
        "",
    ]
    if block_training_bots:
        lines += [
            "# --- Pure training-data bots (blocked: no search/answer visibility",
            "# --- benefit; remove these blocks if you don't mind AI training) ---",
            "User-agent: CCBot",
            "Disallow: /",
            "",
            "User-agent: Bytespider",
            "Disallow: /",
            "",
            "User-agent: Google-Extended",
            "Disallow: /",
            "",
            "User-agent: Applebot-Extended",
            "Disallow: /",
            "",
        ]
    lines.append(f"Sitemap: {origin}/sitemap.xml")
    return "\n".join(lines) + "\n"


def llms_txt_template(url: str, brand: str, description: str = "",
                      key_pages: list = None) -> str:
    origin = _origin(url)
    key_pages = key_pages or []
    lines = [
        f"# {brand}",
        "",
        f"> {description or 'One-sentence description of what ' + brand + ' does and who it serves. EDIT ME.'}",
        "",
        "## Key pages",
        "",
    ]
    for page_url, title in key_pages[:10]:
        lines.append(f"- [{title or page_url}]({page_url})")
    if not key_pages:
        lines += [f"- [Home]({origin}/)",
                  f"- [About]({origin}/about)  <!-- EDIT: real URLs -->",
                  f"- [Services]({origin}/services)",
                  f"- [Contact]({origin}/contact)"]
    lines += [
        "",
        "## About",
        "",
        f"EDIT ME: 2-3 short paragraphs about {brand} - what you offer, where "
        "you operate, and what makes you credible. AI engines use this file to "
        "understand and cite your site accurately.",
        "",
    ]
    return "\n".join(lines)


def organization_schema_template(url: str, brand: str,
                                 socials: dict = None) -> str:
    origin = _origin(url)
    schema = {
        "@context": "https://schema.org",
        "@type": "Organization",
        "name": brand,
        "url": origin + "/",
        "logo": origin + "/logo.png",
        "description": "EDIT ME: one-sentence description of the business.",
        "sameAs": list((socials or {}).values()) or [
            "https://www.facebook.com/EDIT-ME",
            "https://www.linkedin.com/company/EDIT-ME",
        ],
        "contactPoint": {
            "@type": "ContactPoint",
            "telephone": "+1-555-555-5555",
            "contactType": "customer service",
        },
    }
    return ('<script type="application/ld+json">\n'
            + json.dumps(schema, indent=2)
            + "\n</script>\n")


def local_business_schema_template(url: str, brand: str) -> str:
    origin = _origin(url)
    schema = {
        "@context": "https://schema.org",
        "@type": "LocalBusiness",
        "name": brand,
        "url": origin + "/",
        "image": origin + "/storefront.jpg",
        "telephone": "+1-555-555-5555",
        "address": {
            "@type": "PostalAddress",
            "streetAddress": "123 Main St",
            "addressLocality": "City",
            "addressRegion": "ST",
            "postalCode": "00000",
            "addressCountry": "US",
        },
        "geo": {"@type": "GeoCoordinates", "latitude": 0.0, "longitude": 0.0},
        "openingHoursSpecification": [{
            "@type": "OpeningHoursSpecification",
            "dayOfWeek": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
            "opens": "09:00",
            "closes": "17:00",
        }],
        "priceRange": "$$",
    }
    return ('<script type="application/ld+json">\n'
            + json.dumps(schema, indent=2)
            + "\n</script>\n")


def faq_schema_template() -> str:
    schema = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [
            {
                "@type": "Question",
                "name": "EDIT ME: a real question customers ask?",
                "acceptedAnswer": {
                    "@type": "Answer",
                    "text": "EDIT ME: a clear, complete answer (40-60 words works "
                            "well for AI answer engines and featured snippets).",
                },
            },
            {
                "@type": "Question",
                "name": "EDIT ME: second question?",
                "acceptedAnswer": {"@type": "Answer", "text": "EDIT ME: answer."},
            },
        ],
    }
    return ('<script type="application/ld+json">\n'
            + json.dumps(schema, indent=2)
            + "\n</script>\n")


def htaccess_snippet() -> str:
    return """# .htaccess performance & SEO snippet - generated by SEO Audit Pro
# (Apache hosts only. Merge with your existing .htaccess - do not just overwrite.)

RewriteEngine On

# 1) Force HTTPS (safe on any host - never redirects to itself)
RewriteCond %{HTTPS} off
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

# 2) Canonical host (pick ONE canonical hostname). This block is separate from
#    the HTTPS rule above so it can't loop. EDIT the two lines below:
#      - set CANONICAL to your chosen host (with or without www)
#      - the condition matches every OTHER host and sends it to CANONICAL
#    Example canonicalizes to the non-www apex; swap the values for www.
#
#   RewriteCond %{HTTP_HOST} !^example\\.com$ [NC]
#   RewriteRule ^ https://example.com%{REQUEST_URI} [L,R=301]
#
# (To canonicalize to www instead:
#   RewriteCond %{HTTP_HOST} !^www\\.example\\.com$ [NC]
#   RewriteRule ^ https://www.example.com%{REQUEST_URI} [L,R=301] )

# Compression
<IfModule mod_deflate.c>
  AddOutputFilterByType DEFLATE text/html text/css application/javascript application/json image/svg+xml
</IfModule>

# Browser caching for static assets
<IfModule mod_expires.c>
  ExpiresActive On
  ExpiresByType image/webp "access plus 1 year"
  ExpiresByType image/avif "access plus 1 year"
  ExpiresByType image/png  "access plus 1 year"
  ExpiresByType image/jpeg "access plus 1 year"
  ExpiresByType text/css   "access plus 1 month"
  ExpiresByType application/javascript "access plus 1 month"
</IfModule>

# Security headers
<IfModule mod_headers.c>
  Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains"
  Header always set X-Content-Type-Options "nosniff"
</IfModule>
"""


def write_fix_files(output_dir, url: str, brand: str, socials: dict = None,
                    key_pages: list = None, is_local: bool = False):
    """Write all fix templates into <output_dir>/fixes/. Returns paths."""
    import os
    fixes_dir = os.path.join(output_dir, "fixes")
    os.makedirs(fixes_dir, exist_ok=True)
    files = {
        "robots.txt": recommended_robots_txt(url),
        "llms.txt": llms_txt_template(url, brand, key_pages=key_pages),
        "organization-schema.html": organization_schema_template(url, brand, socials),
        "faq-schema.html": faq_schema_template(),
        "htaccess-snippet.txt": htaccess_snippet(),
        "README-FIXES.txt": (
            "HOW TO USE THESE FILES\n"
            "======================\n"
            "1. robots.txt        -> review, edit, upload to your site root "
            "(https://yoursite.com/robots.txt)\n"
            "2. llms.txt          -> fill in the EDIT ME parts, upload to site root\n"
            "3. organization-schema.html -> fill in real details, paste into the "
            "<head> of your homepage\n"
            "4. local-business-schema.html (if generated) -> fill in real NAP "
            "details, paste into homepage/contact page <head>\n"
            "5. faq-schema.html   -> replace with your real FAQs, paste into the "
            "page that shows those FAQs (the visible text must match)\n"
            "6. htaccess-snippet.txt -> Apache hosts only; merge carefully with "
            "your existing .htaccess\n\n"
            "Validate schema after uploading:\n"
            "  - https://search.google.com/test/rich-results\n"
            "  - https://validator.schema.org/\n"
        ),
    }
    if is_local:
        files["local-business-schema.html"] = local_business_schema_template(url, brand)
    paths = []
    for name, content in files.items():
        path = os.path.join(fixes_dir, name)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(content)
        paths.append(path)
    return paths
